### ISSUE TITLE
Not compatible with minecolonies

### ISSUE THREAD

**Issue by TheRTGGaming** [CJMinecraft01/OreClumps#6]
[crash-2022-09-12_16.22.29-server.txt](https://github.com/CJMinecraft01/OreClumps/files/9552465/crash-2022-09-12_16.22.29-server.txt)

mod is not working with minecolonies-1.19.2-1.0.1028-BETA

**Comment by CJMinecraft01** [comment]
Hi there! Thanks for reporting this! This should hopefully be fixed in the latest version :)
